sudo: required

language: bash

services:
  - docker

after_success:
  - export REPO=aswinkarthik/neovim-dotfiles
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build . -f Dockerfile -t "$REPO:$TRAVIS_COMMIT"
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:$TAG
  - docker tag $REPO:$TRAVIS_COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
